### ISSUE TITLE
No unused var が TypeScript でうまく動いていない

### ISSUE THREAD

**Issue by kamataryo** [geolonia/eslint-config#4]
<img width="557" alt="スクリーンショット 2021-08-27 19 01 19" src="https://user-images.githubusercontent.com/6292312/131110242-e9be0299-b404-47e7-856c-ca18187879eb.png">

**Comment by keichan34** [comment]
これはタイプのために使ってるだけだから _key in XYZ でいいかな。。

**Comment by kamataryo** [comment]
静的解析側の都合でコードに手を入れたくないなと。以下の設定で競合を解消してくれるかもしれないので、また試します。
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md#how-to-use

**Comment by kamataryo** [comment]
うまくいきました。
